### ISSUE TITLE
reCAPTCHA Invisble plugin fails execution after Joomla! Core update 5.2.0

### ISSUE THREAD

**Issue by maggus** [joomla/joomla-cms#44294]
### Steps to reproduce the issue

- Install Joomla! 5.2.0
- Activate reCAPTCHA Invisible Plugin
- Go to Joomla's password reset page in frontend

### Expected result

reCAPTCHA should be executed without error messages, but the plugin does not appear. 

### Actual result

Error message appears in development console:

`recaptcha.min.js?261654:5 Uncaught (in promise) TypeError: s.getElementsByClassName(...).forEach is not a function
    at a.JoomlainitReCaptchaInvisible (recaptcha.min.js?261654:5:182)`

### System information (as much as possible)

Joomla! 5.2.0

### Additional comments

This issue seems to be present since Joomla! 5.2.0. In Joomla! 5.1.4 everything was working fine.

**Comment by drmenzelit** [comment]
Which reCaptcha plugin are you using?

**Comment by Fedik** [comment]
Joomla 5 does not provide any Captcha, however while update from 4 to 5 we keep reCAPTCHA Invisible Plugin from Joomla 4.

From quick look j4 reCAPTCHA does not have such code as in your reaport, probably something mixed with your update.
You can try to copy `media/plg_captcha_recaptcha_invisible/js/` folder from latest j4. But make backup of course.

**Comment by cmirnow** [comment]
> reCAPTCHA should be executed without error messages, but the plugin does not appear.
> 
> This issue seems to be present since Joomla! 5.2.0. In Joomla! 5.1.4 everything was working fine.

I have a similar problem. After updating Joomla from 5.1.4 to 5.2.0  **reCAPTCHA Invisble plugin** stops working. 
Any ideas?

**Comment by maggus** [comment]
@Fedik Both Joomla! 5.2.0 Stable Full Package and Stable Update Package ship captcha files for reCAPTCHA Invisible,
see `media/plg_captcha_recaptcha_invisible`.

Please double check your statement that Joomla! 5 does not provide any files for reCAPTCHA Invisible.

**Comment by maggus** [comment]
@drmenzelit I am using Joomla! 5 and reCAPTCHA Invisible. As far as I know reCAPTCHA Visible has been removed with Joomla! 5 upgrade.

**Comment by Fedik** [comment]
> Both Joomla! 5.2.0 Stable Full Package and Stable Update Package ship captcha files for reCAPTCHA Invisible,
see media/plg_captcha_recaptcha_invisible

And that is another bug. 
Copy js files from prev version as a temporary fix, that should help, untill  someoen will find a better fix.

**Comment by brianteeman** [comment]
The problem is that the media files were incorrectly added to the list of files to be removed from existing installs
https://github.com/joomla/joomla-cms/blob/59b1341c503ce431382a52561e48efaf03af9d2f/administrator/components/com_admin/script.php#L1247-L1249

**Comment by Fedik** [comment]
Please test the fix https://github.com/joomla/joomla-cms/pull/44306

**Comment by tschombes** [comment]
@fgsw 
Maybe i dont get it how to use your fix on a live site, do you have any hints how to use it without reinstallation of J4?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44294">issues.joomla.org/tracker/joomla-cms/44294</a>.</sub>

**Comment by tschombes** [comment]
So i testet the fix like the following:

I restored the original Joomla 5.2 files, which i changed before against the 5.1.4 ones.

After that, i replaced the recaptcha.js file against the one from #44306 

But it does not work, the invisible Recaptcha Logo does not appear at any form.

I then changed the three files against the Joomla 5.1.4 ones again and the invisible recaptcha works fine.

So the fix is not working on my site.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44294">issues.joomla.org/tracker/joomla-cms/44294</a>.</sub>

**Comment by tschombes** [comment]
Same Problem with Joomla 5.2.1

Fix from ##44306 does not work, had to replace the 3 files with the Joomla 5.1.4 ones to make the invisible recaptcha plugin working again

**Comment by richard67** [comment]
> Same Problem with Joomla 5.2.1
> 
> Fix from #[#44306](https://github.com/joomla/joomla-cms/pull/44306) does not work, had to replace the 3 files with the Joomla 5.1.4 ones to make the invisible recaptcha plugin working again

@tschombes How did you apply the fix from PR #44306 ? As that PR has not been merged yet, it is of course not included in 5.2.1. If you want to help that it becomes included in the upcoming 5.2.2, you can test that PR, because every PR needs 2 successful human test before it can be merged.

One way to apply the PR would be to download the update zip for that PR here
https://artifacts.joomla.org/drone/joomla/joomla-cms/5.2-dev/44306/downloads/80218/
and unpack the following files from that zip:
- media/plg_captcha_recaptcha_invisible/js/recaptcha.js
- media/plg_captcha_recaptcha_invisible/js/recaptcha.min.js
- media/plg_captcha_recaptcha_invisible/js/recaptcha.min.js.gz

Then backup the existing 3 files on your site which you had copied from 5.5.1 and then replace the existing files by the one unpacked from the zip. Finally clear your browser cache to make sure your browser doesn't use the old, cached files and test if it works. Please report back the result in PR #44306 . Thanks in advance.

**Comment by dragonpil** [comment]
I tested the 3 recaptcha files on my 5.2.1 installation and now it works again <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44294">issues.joomla.org/tracker/joomla-cms/44294</a>.</sub>
