### ISSUE TITLE
Too few arguments to function PlgSystemFields::onContentAfterSave()

### ISSUE THREAD

**Issue by go-source** [joomla/joomla-cms#23396]
### Steps to reproduce the issue
create a content plugin that triggers onContentAfterSave 
My plugin works fine in backend (any Joomla or PHP version)
In the frontend it works fine with PHP 7.0.x. It breaks and shows error message with PHP 7.1 and above

### Expected result
No error

### Actual result
Too few arguments to function PlgSystemFields::onContentAfterSave(), 2 passed in /home/.../public_html/libraries/joomla/event/event.php on line 70 and at least 3 expected 

Call stack
# 	Function 	Location
1 	() 	        JROOT/plugins/system/fields/fields.php:43
2 	PlgSystemFields->onContentAfterSave() 	JROOT/libraries/joomla/event/event.php:70
3 	JEvent->update() 	                JROOT/libraries/joomla/event/dispatcher.php:160
4 	JEventDispatcher->trigger() 	        JROOT/components/com_gsimporter/models/logform.php:350 

### System information (as much as possible)
Joomla 3.7, 3.8 and 3.9 - error irrespective to Joomla version
PHP 7.0.x no error
PHP 7.1 and above with error

### Additional comments
original Joomla code is:
JROOT/libraries/joomla/event/event.php:70 => return call_user_func_array(array($this, $event), $args);

I suggest to add an argument to eliminate error - this solves the issue:
return call_user_func_array(array($this, $event), $args, 0);

**Comment by chmst** [comment]
https://issues.joomla.org/tracker/joomla-cms/23395 Can you test this? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23396">issues.joomla.org/tracker/joomla-cms/23396</a>.</sub>

**Comment by Quy** [comment]
@chmst This issue is for v3.

**Comment by chmst** [comment]
oops sorry

**Comment by SharkyKZ** [comment]
Can't reproduce this on core.

Looks like `com_gsimporter` passes only 2 arguments but it should be at least 3 in 3.x. See documentation https://docs.joomla.org/Plugin/Events/Content#onContentAfterSave.

**Comment by ghost** [comment]
closed as stated above.
